import java.util.*;

class myexception extends Exception{
	public myexception(String st)
	{
		super(st);
	}
}
class Student
{
	int roll_no,age;
	String name,course;
	public Student(int roll_no,String name,int age, String course)
	{
		this.roll_no=roll_no;
		this.name=name;
		this.age=age;
		this.course=course;
	}
	void check() throws  myexception
	{
		System.out.println("Roll no: "+roll_no);
		System.out.println("Name: "+ name);
		System.out.println("Age: "+age);
		System.out.println("Course: "+ course);
		if(age>=15 && age<=21)
		{
			System.out.println("Age within range");
		}
		else
		{
			System.out.println("Age not within range");
		}
	}
	public static void main(String args[])
	{
		Student s=new Student(01,"varad",19,"BScIT");
		try
		{
		s.check();
		}
	catch(myexception e)
	{
		System.out.println(e);
	}
}
}

/////ACCOUNT

import java.util.*;
class exception extends Exception
{
	public exception(String st)
	{
		super(st);
	}
}
class Account
{
	int accno;
	String name;
	double balance;
	
	public Account(int accno,String name,double balance)
	{
		this.accno = accno;
		this.name = name;
		this.balance = balance;	
	}
	
	void check() throws exception
	{
		System.out.println("Enter the account no:" +accno);
		System.out.println("Enter the name:" +name);
       System.out.println("Enter the balnce:" +balance);
if(balance>=1000 && balance <= 5000)
{
System.out.println("in range");	
}
else
{
	System.out.println("not in range");
}
	}

public static void main(String s3[])
{
	Account a = new Account(12,"varad",4500);
	try
	{
	a.check();
	}
	catch(exception e)
	{
		System.out.println(e);
	}
}
	}
